name: Pytest with codecov

on:
  # Run each time we push and pull requests
  push:
  pull_request:
  # Cron job
  # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule
  schedule:
    # https://crontab.guru/#0_0_1_*_*
    - cron: '0 0 1 * *'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      # Use the v1 tag of: https://github.com/actions/checkout
      uses: actions/checkout@v1

    - name: Setup Python
      # Use the master branch of: https://github.com/actions/setup-python
      uses: actions/setup-python@master
      with:
        version: 3.7

    - name: Setting up BOUT-dev next
      run: |
        cd ${HOME}/BOUT-dev
        git clone git://github.com/boutproject/BOUT-dev.git ${HOME}/BOUT-dev
        git checkout next
        ./configure
        make
        cd -

    - name: Generate coverage report
      # Install and run the coverage report
      run: |
        pip install -r requirements.txt
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      # Use the v1 tag of: https://github.com/codecov/codecov-action
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        yml: ./codecov.yml